import './App.css';
import { useState } from 'react';
import * as XLSX from 'xlsx';

import ExcelDisplay from './components/ExcelDisplay';
function App() {
  const [excelData, setExcelData] = useState<any>([]);

  // useEffect(() => {
  //   // console.log(excelData);
  // }, [excelData]);

  const handleDownload = async () => {
    let arrayOfArrays: any = [];
    for (let sortedRow of excelData) {
      arrayOfArrays = [
        ...arrayOfArrays,
        [
          [sortedRow.statistical_period],
          [sortedRow.year],
          [sortedRow.month],
          [sortedRow.day],
          [sortedRow.longDay],
          [sortedRow.hour],
          [sortedRow.serialNumber],
          [sortedRow.responsabil],
          [sortedRow.global_irradiation],
          [sortedRow.average_temperature],
          [sortedRow.theoretical_yield_kWh],
          [sortedRow.PV_yield_kWh],
          [sortedRow.inverter_yield],
          [sortedRow.export_kWh],
          [sortedRow.loss_due_to_export_limitation_kWh],
          [sortedRow.loss_due_to_export_limitation_EUR],
          [sortedRow.revenue_EUR],
        ],
      ];
    }
    const downloadData = [
      ['Plant Report'],
      [
        'Statistical Period',
        'Year',
        'Month',
        'Day',
        'Long Day',
        'Hour',
        'Inverter serial code',
        'Report generated by',
        'Global Irradiation (kWh/㎡)',
        'Average Temperature(°C)',
        'Theoretical Yield (kWh)',
        'PV Yield (kWh)',
        'Inverter Yield (kWh)',
        'Export (kWh)',
        'Loss Due to Export Limitation (kWh',
        'Loss Due to Export Limitation(€)',
        'Revenue (€)',
      ],
      ...arrayOfArrays,
    ];

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(downloadData);

    XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');

    await XLSX.writeFile(wb, 'raport_invertoare.xlsx');
  };

  return (
    <div>
      <button onClick={handleDownload}>Download</button>
      <ExcelDisplay excelData={excelData} setExcelData={setExcelData} />
    </div>
  );
}

export default App;
